
version: 2.1

orbs: 
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout  # check out source code to working directory

      - run: sudo chown -R circleci:circleci /usr/local/bin

      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages

      - restore_cache:
          name: Restore Python Dependencies Cache

          key: v1-deps-{{ checksum "Pipfile.lock" }}

      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Install Dependencies

          command: pip install -r requirements.txt

      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          name: Cache Python dependencies

          key: v1-deps-{{ checksum "Pipfile.lock" }}

          paths:
            - "venv"

      - run:
          name: Run tests

          command: python manage.py test

      - run:
          name: Run test coverage

          command: coverage run --source="willApp" manage.py test&&coverage report -m


workflows:
  sample:
  
    jobs:
      - build-and-test
